import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

export const languages = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'hi', name: 'हिंदी', flag: '🇮🇳' },
  { code: 'bn', name: 'বাংলা', flag: '🇧🇩' },
  { code: 'ta', name: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'తెలుగు', flag: '🇮🇳' },
];

const resources = {
  en: {
    translation: {
      "nav.home": "Home",
      "nav.categories": "Categories",
      "nav.symptomChecker": "Symptom Checker",
      "nav.about": "About",
      "nav.emergency": "Emergency",
      "language": "Language",
      "hero.title": "Quick First Aid Guidance at Your Fingertips",
      "hero.subtitle": "Access reliable first aid information when you need it most. RapAID provides clear, step-by-step instructions for various emergency situations.",
      "hero.explore": "Explore Categories",
      "hero.emergencyBtn": "Emergency",
      "hero.badge": "🚨 Emergency First Aid Assistant",
      "search.placeholder": "Search for first aid guides...",
      "commonEmergencies.title": "Common Emergencies",
      "commonEmergencies.subtitle": "Quick access to guides for frequently encountered situations.",
      "categories.title": "Emergency Categories",
      "categories.subtitle": "Browse through our comprehensive categories of emergency first aid guides. Each category contains detailed step-by-step instructions.",
      "categories.viewAll": "View All Categories",
      "symptomChecker.title": "Advanced Symptom Checker",
      "symptomChecker.subtitle": "Not sure what's wrong? Describe your symptoms and our AI will help identify the possible condition and provide appropriate first aid guidance.",
      "symptomChecker.checkNow": "Check Symptoms Now",
      "symptomChecker.aiBadge": "AI-Powered",
      "symptomChecker.commonSymptoms": "Common Symptoms",
      "symptomChecker.possibleCondition": "Possible Condition: Heart Attack",
      "symptomChecker.conditionDetail": "Symptoms may indicate a cardiac emergency. Seek immediate medical attention.",
      "symptomChecker.viewGuide": "View First Aid Guide",
      "features.title": "Essential Features",
      "features.subtitle": "RapAID provides crucial features to help you respond effectively to emergencies.",
      "feature.stepByStep": "Step-by-Step Guides",
      "feature.stepByStepDesc": "Clear, concise instructions with visual aids for various emergency situations.",
      "feature.offline": "Offline Access",
      "feature.offlineDesc": "Access critical first aid information even without an internet connection.",
      "feature.voice": "Voice Assistance",
      "feature.voiceDesc": "Hands-free guidance through voice commands and audio instructions.",
      "multiLanguage.title": "Multiple Language Support",
      "multiLanguage.subtitle": "RapAID offers first aid instructions in multiple Indian languages for greater accessibility.",
      "footer.quickLinks": "Quick Links",
      "footer.categories": "Emergency Categories",
      "footer.contact": "Emergency Contact",
      "footer.contactDesc": "In case of emergency, please call your local emergency services.",
      "footer.copyright": "© 2026 RapAID. All rights reserved.",
      "footer.disclaimer": "Disclaimer: This application provides first aid guidance for informational purposes only and is not a substitute for professional medical advice or treatment.",
      "footer.logoAlt": "RapAID Logo",
      "footer.description": "Providing quick, reliable first aid guidance when it matters most.",
      "categoriesPage.title": "Emergency Categories",
      "categoriesPage.subtitle": "Browse through our comprehensive categories of emergency first aid guides. Each category contains detailed step-by-step instructions.",
      "categoriesPage.allEmergencies": "All Emergencies",
      "categoriesPage.guidesCount": "{{count}} emergency guides",
      "categoriesPage.viewCategory": "View category",
      "categoriesPage.noResults": "No emergencies found matching \"{{query}}\"",
      "categoriesPage.clearSearch": "Clear search",
      "categoryDetailPage.back": "Back to Categories",
      "categoryDetailPage.guidesCount": "Emergency Guides ({{count}})",
      "categoryDetailPage.selectGuide": "Select an emergency to view detailed first aid instructions.",
      "categoryDetailPage.viewGuide": "View Guide",
      "categoryDetailPage.disclaimerTitle": "Important Disclaimer",
      "categoryDetailPage.disclaimerText": "This information is not a substitute for professional medical advice. In case of emergency, always call emergency services immediately. RapAID is for informational purposes only.",
      "categoryDetailPage.notFoundTitle": "Category Not Found",
      "categoryDetailPage.notFoundText": "Sorry, we couldn't find the category you were looking for.",
      "emergencyGuidePage.notFoundTitle": "Emergency Guide Not Found",
      "emergencyGuidePage.notFoundText": "Sorry, we couldn't find the guide you were looking for.",
      "emergencyGuidePage.backToCategories": "Back to Categories",
      "emergencyGuidePage.alertTitle": "Emergency Situation",
      "emergencyGuidePage.alertDescription": "Always call emergency services if the situation is severe.",
      "symptomCheckerPage.aiBadge": "🤖 AI-Powered",
      "symptomCheckerPage.title": "Symptom Checker",
      "symptomCheckerPage.subtitle": "Describe your symptoms and our AI will help identify the possible condition and provide appropriate first aid guidance.",
      "symptomCheckerPage.describeSymptomsTitle": "Describe your symptoms",
      "symptomCheckerPage.describeSymptomsDesc": "Be specific about what you're feeling, location of pain or discomfort, and when it started.",
      "symptomCheckerPage.textareaPlaceholder": "Example: I'm experiencing chest pain that radiates to my left arm, shortness of breath, and sweating.",
      "symptomCheckerPage.detailsPrompt": "The more details you provide, the better the AI can assist you.",
      "symptomCheckerPage.analyzeButton": "Check Symptoms",
      "symptomCheckerPage.analyzingButton": "Analyzing...",
      "symptomCheckerPage.analysisCompleteTitle": "Analysis complete",
      "symptomCheckerPage.analysisCompleteDesc": "Review the possible conditions and first aid recommendations.",
      "symptomCheckerPage.analysisFailedTitle": "Analysis failed",
      "symptomCheckerPage.analysisFailedDesc": "Unable to analyze symptoms. Please try again.",
      "symptomCheckerPage.errorTitle": "Error",
      "symptomCheckerPage.errorDesc": "Something went wrong. Please try again.",
      "symptomCheckerPage.pleaseEnterSymptomsTitle": "Please enter symptoms",
      "symptomCheckerPage.pleaseEnterSymptomsDesc": "Describe your symptoms to get an analysis.",
      "symptomCheckerPage.results.confidence": "Confidence: {{confidence}}%",
      "symptomCheckerPage.results.relatedSymptoms": "Related Symptoms",
      "symptomCheckerPage.results.firstAidSteps": "Immediate First Aid Steps",
      "symptomCheckerPage.results.viewDetailedGuide": "View Detailed First Aid Guide",
      "symptomCheckerPage.results.emergencyWarningTitle": "Emergency Situation Detected",
      "symptomCheckerPage.results.emergencyWarningText": "Based on the symptoms described, this may be a medical emergency. Call emergency services immediately.",
      "symptomCheckerPage.results.callEmergency": "Call Emergency Services",
      "symptomCheckerPage.disclaimerTitle": "Medical Disclaimer",
      "symptomCheckerPage.disclaimerText": "This application provides first aid guidance for informational purposes only and is not a substitute for professional medical advice or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.",
      "aboutPage.title": "About First Aid Companion",
      "aboutPage.missionTitle": "Our Mission",
      "aboutPage.missionText1": "First Aid Companion is dedicated to providing accessible, easy-to-follow emergency first aid guides to help people respond effectively in critical situations until professional medical help arrives.",
      "aboutPage.missionText2": "Our mission is to empower individuals with the knowledge and confidence to take immediate action during medical emergencies, potentially saving lives and reducing the severity of injuries.",
      "aboutPage.approachTitle": "Our Approach",
      "aboutPage.approachSubtitle": "We believe that first aid information should be:",
      "aboutPage.feature.clear.title": "Clear & Accessible",
      "aboutPage.feature.clear.desc": "Easy to understand instructions that can be followed under stress.",
      "aboutPage.feature.quick.title": "Quick to Access",
      "aboutPage.feature.quick.desc": "Information that can be found and applied rapidly in emergency situations.",
      "aboutPage.feature.evidence.title": "Evidence-Based",
      "aboutPage.feature.evidence.desc": "Updated regularly with the latest medical guidelines and best practices.",
      "aboutPage.feature.supportive.title": "Supportive",
      "aboutPage.feature.supportive.desc": "Designed to guide and reassure during stressful emergency situations.",
      "aboutPage.contactTitle": "Contact Us",
      "aboutPage.contactEmail": "Email:",
      "aboutPage.contactText": "We're always looking to improve our application. Please reach out with any questions, suggestions, or feedback.",
      "aboutPage.disclaimerTitle": "Important Disclaimer",
      "aboutPage.disclaimerText1": "The information provided in First Aid Companion is for educational purposes only and is not a substitute for professional medical advice, diagnosis, or treatment.",
      "aboutPage.disclaimerText2": "Always seek the advice of a qualified healthcare provider with any questions you may have regarding a medical condition or emergency. Never disregard professional medical advice or delay in seeking it because of something you have read on this website.",
      "aboutPage.disclaimerText3": "In case of emergency, please call your local emergency services immediately.",
      "header.logoAlt": "RapAID Logo",
    }
  },
  hi: {
    translation: {
      "nav.home": "होम",
      "nav.categories": "श्रेणियाँ",
      "nav.symptomChecker": "लक्षण जाँचकर्ता",
      "nav.about": "हमारे बारे में",
      "nav.emergency": "आपातकाल",
      "language": "भाषा",
      "hero.title": "आपके हाथों में त्वरित प्राथमिक चिकित्सा मार्गदर्शन",
      "hero.subtitle": "जब आपको सबसे ज्यादा जरूरत हो तब विश्वसनीय प्राथमिक चिकित्सा जानकारी प्राप्त करें। रैपएड विभिन्न आपातकालीन स्थितियों के लिए स्पष्ट, चरण-दर-चरण निर्देश प्रदान करता है।",
      "hero.explore": "श्रेणियाँ एक्सप्लोर करें",
      "hero.emergencyBtn": "आपातकाल",
      "hero.badge": "🚨 आपातकालीन प्राथमिक चिकित्सा सहायक",
      "search.placeholder": "प्राथमिक चिकित्सा गाइड खोजें...",
      "commonEmergencies.title": "सामान्य आपात स्थितियाँ",
      "commonEmergencies.subtitle": "अक्सर होने वाली स्थितियों के लिए गाइड तक त्वरित पहुँच।",
      "categories.title": "आपातकालीन श्रेणियाँ",
      "categories.subtitle": "आपातकालीन प्राथमिक चिकित्सा गाइड की हमारी व्यापक श्रेणियों को ब्राउज़ करें। प्रत्येक श्रेणी में विस्तृत चरण-दर-चरण निर्देश हैं।",
      "categories.viewAll": "सभी श्रेणियाँ देखें",
      "symptomChecker.title": "उन्नत लक्षण परीक्षक",
      "symptomChecker.subtitle": "निश्चित नहीं कि क्या गलत है? अपने लक्षणों का वर्णन करें और हमारा AI संभावित स्थिति की पहचान करने और उचित प्राथमिक चिकित्सा मार्गदर्शन प्रदान करने में मदद करेगा।",
      "symptomChecker.checkNow": "अभी लक्षण जांचें",
      "symptomChecker.aiBadge": "AI-संचालित",
      "symptomChecker.commonSymptoms": "सामान्य लक्षण",
      "symptomChecker.possibleCondition": "संभावित स्थिति: दिल का दौरा",
      "symptomChecker.conditionDetail": "लक्षण हृदय संबंधी आपातकाल का संकेत दे सकते हैं। तत्काल चिकित्सा सहायता लें।",
      "symptomChecker.viewGuide": "प्राथमिक उपचार गाइड देखें",
      "features.title": "आवश्यक सुविधाएँ",
      "features.subtitle": "रैपएड आपको आपात स्थितियों का प्रभावी ढंग से जवाब देने में मदद करने के लिए महत्वपूर्ण सुविधाएँ प्रदान करता है।",
      "feature.stepByStep": "चरण-दर-चरण गाइड",
      "feature.stepByStepDesc": "विभिन्न आपातकालीन स्थितियों के लिए दृश्य सहायता के साथ स्पष्ट, संक्षिप्त निर्देश।",
      "feature.offline": "ऑफलाइन पहुँच",
      "feature.offlineDesc": "इंटरनेट कनेक्शन के बिना भी महत्वपूर्ण प्राथमिक चिकित्सा जानकारी तक पहुँचें।",
      "feature.voice": "आवाज सहायता",
      "feature.voiceDesc": "आवाज आदेशों और ऑडियो निर्देशों के माध्यम से हाथों से मुक्त मार्गदर्शन।",
      "multiLanguage.title": "एकाधिक भाषा समर्थन",
      "multiLanguage.subtitle": "रैपएड अधिक पहुंच के लिए कई भारतीय भाषाओं में प्राथमिक उपचार निर्देश प्रदान करता है।",
      "footer.quickLinks": "त्वरित लिंक्स",
      "footer.categories": "आपातकालीन श्रेणियाँ",
      "footer.contact": "आपातकालीन संपर्क",
      "footer.contactDesc": "आपातकाल की स्थिति में, कृपया अपनी स्थानीय आपातकालीन सेवाओं को कॉल करें।",
      "footer.copyright": "© 2025 रैपएड। सर्वाधिकार सुरक्षित।",
      "footer.disclaimer": "अस्वीकरण: यह एप्लिकेशन केवल सूचनात्मक उद्देश्यों के लिए प्राथमिक उपचार मार्गदर्शन प्रदान करता है और पेशेवर चिकित्सा सलाह या उपचार का विकल्प नहीं है।",
      "footer.logoAlt": "रैपएड लोगो",
      "footer.description": "जब सबसे ज्यादा जरूरत हो, तब त्वरित, विश्वसनीय प्राथमिक उपचार मार्गदर्शन प्रदान करना।",
      "categoriesPage.title": "आपातकालीन श्रेणियाँ",
      "categoriesPage.subtitle": "आपातकालीन प्राथमिक चिकित्सा गाइड की हमारी व्यापक श्रेणियों को ब्राउज़ करें। प्रत्येक श्रेणी में विस्तृत चरण-दर-चरण निर्देश हैं।",
      "categoriesPage.allEmergencies": "सभी आपात स्थितियाँ",
      "categoriesPage.guidesCount": "{{count}} आपातकालीन गाइड",
      "categoriesPage.viewCategory": "श्रेणी देखें",
      "categoriesPage.noResults": "\"{{query}}\" से मेल खाने वाली कोई आपात स्थिति नहीं मिली",
      "categoriesPage.clearSearch": "खोज साफ़ करें",
      "categoryDetailPage.back": "श्रेणियों पर वापस जाएं",
      "categoryDetailPage.guidesCount": "आपातकालीन गाइड ({{count}})",
      "categoryDetailPage.selectGuide": "विस्तृत प्राथमिक उपचार निर्देशों को देखने के लिए एक आपात स्थिति चुनें।",
      "categoryDetailPage.viewGuide": "गाइड देखें",
      "categoryDetailPage.disclaimerTitle": "महत्वपूर्ण अस्वीकरण",
      "categoryDetailPage.disclaimerText": "यह जानकारी पेशेवर चिकित्सा सलाह का विकल्प नहीं है। आपातकाल की स्थिति में, हमेशा तुरंत आपातकालीन सेवाओं को कॉल करें। रैपएड केवल सूचनात्मक उद्देश्यों के लिए है।",
      "categoryDetailPage.notFoundTitle": "श्रेणी नहीं मिली",
      "categoryDetailPage.notFoundText": "क्षमा करें, आप जिस श्रेणी की तलाश कर रहे थे, वह हमें नहीं मिली।",
      "emergencyGuidePage.notFoundTitle": "आपातकालीन गाइड नहीं मिला",
      "emergencyGuidePage.notFoundText": "क्षमा करें, आप जिस गाइड की तलाश कर रहे थे, वह हमें नहीं मिला।",
      "emergencyGuidePage.backToCategories": "श्रेणियों पर वापस जाएं",
      "emergencyGuidePage.alertTitle": "आपातकालीन स्थिति",
      "emergencyGuidePage.alertDescription": "यदि स्थिति गंभीर हो तो हमेशा आपातकालीन सेवाओं को कॉल करें।",
      "symptomCheckerPage.aiBadge": "🤖 AI-संचालित",
      "symptomCheckerPage.title": "लक्षण जाँचकर्ता",
      "symptomCheckerPage.subtitle": "अपने लक्षणों का वर्णन करें और हमारा AI संभावित स्थिति की पहचान करने और उचित प्राथमिक चिकित्सा मार्गदर्शन प्रदान करने में मदद करेगा।",
      "symptomCheckerPage.describeSymptomsTitle": "अपने लक्षणों का वर्णन करें",
      "symptomCheckerPage.describeSymptomsDesc": "आप क्या महसूस कर रहे हैं, दर्द या बेचैनी का स्थान और यह कब शुरू हुआ, इसके बारे में विशिष्ट रहें।",
      "symptomCheckerPage.textareaPlaceholder": "उदाहरण: मुझे सीने में दर्द हो रहा है जो मेरे बाएं हाथ तक फैल रहा है, सांस लेने में तकलीफ और पसीना आ रहा है।",
      "symptomCheckerPage.detailsPrompt": "आप जितने अधिक विवरण प्रदान करेंगे, AI उतनी ही बेहतर सहायता कर पाएगा।",
      "symptomCheckerPage.analyzeButton": "लक्षण जांचें",
      "symptomCheckerPage.analyzingButton": "विश्लेषण हो रहा है...",
      "symptomCheckerPage.analysisCompleteTitle": "विश्लेषण पूर्ण",
      "symptomCheckerPage.analysisCompleteDesc": "संभावित स्थितियों और प्राथमिक उपचार सिफारिशों की समीक्षा करें।",
      "symptomCheckerPage.analysisFailedTitle": "विश्लेषण विफल",
      "symptomCheckerPage.analysisFailedDesc": "लक्षणों का विश्लेषण करने में असमर्थ। कृपया पुनः प्रयास करें।",
      "symptomCheckerPage.errorTitle": "त्रुटि",
      "symptomCheckerPage.errorDesc": "कुछ गलत हो गया। कृपया पुनः प्रयास करें।",
      "symptomCheckerPage.pleaseEnterSymptomsTitle": "कृपया लक्षण दर्ज करें",
      "symptomCheckerPage.pleaseEnterSymptomsDesc": "विश्लेषण प्राप्त करने के लिए अपने लक्षणों का वर्णन करें।",
      "symptomCheckerPage.results.confidence": "आत्मविश्वास: {{confidence}}%",
      "symptomCheckerPage.results.relatedSymptoms": "संबंधित लक्षण",
      "symptomCheckerPage.results.firstAidSteps": "तत्काल प्राथमिक उपचार कदम",
      "symptomCheckerPage.results.viewDetailedGuide": "विस्तृत प्राथमिक उपचार गाइड देखें",
      "symptomCheckerPage.results.emergencyWarningTitle": "आपातकालीन स्थिति का पता चला",
      "symptomCheckerPage.results.emergencyWarningText": "वर्णित लक्षणों के आधार पर, यह एक चिकित्सा आपातकाल हो सकता है। तुरंत आपातकालीन सेवाओं को कॉल करें।",
      "symptomCheckerPage.results.callEmergency": "आपातकालीन सेवाओं को कॉल करें",
      "symptomCheckerPage.disclaimerTitle": "चिकित्सा अस्वीकरण",
      "symptomCheckerPage.disclaimerText": "यह एप्लिकेशन केवल सूचनात्मक उद्देश्यों के लिए प्राथमिक उपचार मार्गदर्शन प्रदान करता है और पेशेवर चिकित्सा सलाह या उपचार का विकल्प नहीं है। किसी भी चिकित्सा स्थिति के संबंध में आपके किसी भी प्रश्न के लिए हमेशा अपने चिकित्सक या अन्य योग्य स्वास्थ्य प्रदाता की सलाह लें।",
      "aboutPage.title": "प्राथमिक उपचार साथी के बारे में",
      "aboutPage.missionTitle": "हमारा लक्ष्य",
      "aboutPage.missionText1": "प्राथमिक उपचार साथी सुलभ, आसानी से पालन करने योग्य आपातकालीन प्राथमिक उपचार गाइड प्रदान करने के लिए समर्पित है ताकि लोग पेशेवर चिकित्सा सहायता आने तक महत्वपूर्ण स्थितियों में प्रभावी ढंग से प्रतिक्रिया कर सकें।",
      "aboutPage.missionText2": "हमारा लक्ष्य व्यक्तियों को चिकित्सा आपात स्थितियों के दौरान तत्काल कार्रवाई करने के लिए ज्ञान और आत्मविश्वास के साथ सशक्त बनाना है, संभावित रूप से जीवन बचाना और चोटों की गंभीरता को कम करना है।",
      "aboutPage.approachTitle": "हमारा दृष्टिकोण",
      "aboutPage.approachSubtitle": "हमारा मानना है कि प्राथमिक उपचार की जानकारी होनी चाहिए:",
      "aboutPage.feature.clear.title": "स्पष्ट और सुलभ",
      "aboutPage.feature.clear.desc": "तनाव में पालन किए जा सकने वाले समझने में आसान निर्देश।",
      "aboutPage.feature.quick.title": "त्वरित पहुँच",
      "aboutPage.feature.quick.desc": "आपातकालीन स्थितियों में तेजी से पाई और लागू की जा सकने वाली जानकारी।",
      "aboutPage.feature.evidence.title": "साक्ष्य-आधारित",
      "aboutPage.feature.evidence.desc": "नवीनतम चिकित्सा दिशानिर्देशों और सर्वोत्तम प्रथाओं के साथ नियमित रूप से अपडेट किया जाता है।",
      "aboutPage.feature.supportive.title": "सहयोगी",
      "aboutPage.feature.supportive.desc": "तनावपूर्ण आपातकालीन स्थितियों के दौरान मार्गदर्शन और आश्वस्त करने के लिए डिज़ाइन किया गया।",
      "aboutPage.contactTitle": "हमसे संपर्क करें",
      "aboutPage.contactEmail": "ईमेल:",
      "aboutPage.contactText": "हम हमेशा अपने एप्लिकेशन को बेहतर बनाने की कोशिश कर रहे हैं। कृपया किसी भी प्रश्न, सुझाव या प्रतिक्रिया के लिए संपर्क करें।",
      "aboutPage.disclaimerTitle": "महत्वपूर्ण अस्वीकरण",
      "aboutPage.disclaimerText1": "प्राथमिक उपचार साथी में दी गई जानकारी केवल शैक्षिक उद्देश्यों के लिए है और यह पेशेवर चिकित्सा सलाह, निदान या उपचार का विकल्प नहीं है।",
      "aboutPage.disclaimerText2": "किसी भी चिकित्सा स्थिति या आपातकाल के संबंध में आपके किसी भी प्रश्न के लिए हमेशा एक योग्य स्वास्थ्य सेवा प्रदाता की सलाह लें। इस वेबसाइट पर पढ़ी गई किसी भी चीज़ के कारण कभी भी पेशेवर चिकित्सा सलाह की अवहेलना न करें या इसे प्राप्त करने में देरी न करें।",
      "aboutPage.disclaimerText3": "आपातकाल की स्थिति में, कृपया तुरंत अपनी स्थानीय आपातकालीन सेवाओं को कॉल करें।",
      "header.logoAlt": "रैपएड लोगो",
    }
  },
  bn: {
    translation: {
      "nav.home": "হোম",
      "nav.categories": "বিভাগ",
      "nav.symptomChecker": "লক্ষণ পরীক্ষক",
      "nav.about": "আমাদের সম্পর্কে",
      "nav.emergency": "জরুরী",
      "language": "ভাষা",
      "hero.title": "আপনার হাতের মুঠোয় দ্রুত প্রাথমিক চিকিৎসার নির্দেশিকা",
      "hero.subtitle": "যখন আপনার সবচেয়ে বেশি প্রয়োজন তখন নির্ভরযোগ্য প্রাথমিক চিকিৎসার তথ্য অ্যাক্সেস করুন। RapAID বিভিন্ন জরুরী পরিস্থিতির জন্য পরিষ্কার, ধাপে ধাপে নির্দেশাবলী প্রদান করে।",
      "hero.explore": "বিভাগগুলি অন্বেষণ করুন",
      "hero.emergencyBtn": "জরুরী",
      "hero.badge": "🚨 জরুরী প্রাথমিক চিকিৎসা সহকারী",
      "search.placeholder": "প্রাথমিক চিকিৎসার গাইড অনুসন্ধান করুন...",
      "commonEmergencies.title": "সাধারণ জরুরী অবস্থা",
      "commonEmergencies.subtitle": "প্রায়শই সম্মুখীন হওয়া পরিস্থিতিগুলির জন্য গাইডগুলিতে দ্রুত অ্যাক্সেস।",
      "categories.title": "জরুরী বিভাগ",
      "categories.subtitle": "আমাদের জরুরী প্রাথমিক চিকিৎসার গাইডের ব্যাপক বিভাগগুলির মাধ্যমে ব্রাউজ করুন। প্রতিটি বিভাগে বিস্তারিত ধাপে ধাপে নির্দেশাবলী রয়েছে।",
      "categories.viewAll": "সমস্ত বিভাগ দেখুন",
      "symptomChecker.title": "উন্নত লক্ষণ পরীক্ষক",
      "symptomChecker.subtitle": "নিশ্চিত নন কী সমস্যা? আপনার লক্ষণগুলি বর্ণনা করুন এবং আমাদের AI সম্ভাব্য অবস্থা সনাক্ত করতে এবং উপযুক্ত প্রাথমিক চিকিৎসার নির্দেশিকা প্রদান করতে সহায়তা করবে।",
      "symptomChecker.checkNow": "এখনই লক্ষণ পরীক্ষা করুন",
      "symptomChecker.aiBadge": "AI-চালিত",
      "symptomChecker.commonSymptoms": "সাধারণ লক্ষণ",
      "symptomChecker.possibleCondition": "সম্ভাব্য অবস্থা: হার্ট অ্যাটাক",
      "symptomChecker.conditionDetail": "লক্ষণগুলি কার্ডিয়াক জরুরী অবস্থার ইঙ্গিত দিতে পারে। অবিলম্বে চিকিৎসার সাহায্য নিন।",
      "symptomChecker.viewGuide": "প্রাথমিক চিকিৎসার গাইড দেখুন",
      "features.title": "অপরিহার্য বৈশিষ্ট্য",
      "features.subtitle": "RapAID আপনাকে জরুরী পরিস্থিতিতে কার্যকরভাবে সাড়া দিতে সহায়তা করার জন্য গুরুত্বপূর্ণ বৈশিষ্ট্য সরবরাহ করে।",
      "feature.stepByStep": "ধাপে ধাপে গাইড",
      "feature.stepByStepDesc": "বিভিন্ন জরুরী পরিস্থিতির জন্য ভিজ্যুয়াল সহায়ক সহ পরিষ্কার, সংক্ষিপ্ত নির্দেশাবলী।",
      "feature.offline": "অফলাইন অ্যাক্সেস",
      "feature.offlineDesc": "এমনকি ইন্টারনেট সংযোগ ছাড়াই গুরুত্বপূর্ণ প্রাথমিক চিকিৎসার তথ্য অ্যাক্সেস করুন।",
      "feature.voice": "ভয়েস সহায়তা",
      "feature.voiceDesc": "ভয়েস কমান্ড এবং অডিও নির্দেশাবলীর মাধ্যমে হ্যান্ডস-ফ্রি নির্দেশিকা।",
      "multiLanguage.title": "একাধিক ভাষা সমর্থন",
      "multiLanguage.subtitle": "RapAID বৃহত্তর অ্যাক্সেসযোগ্যতার জন্য একাধিক ভারতীয় ভাষায় প্রাথমিক চিকিৎসার নির্দেশাবলী সরবরাহ করে।",
      "footer.quickLinks": "দ্রুত লিঙ্ক",
      "footer.categories": "জরুরী বিভাগ",
      "footer.contact": "জরুরী যোগাযোগ",
      "footer.contactDesc": "জরুরী পরিস্থিতিতে, দয়া করে আপনার স্থানীয় জরুরী পরিষেবাগুলিতে কল করুন।",
      "footer.copyright": "© 2026 RapAID। সর্বস্বত্ব সংরক্ষিত।",
      "footer.disclaimer": "দাবিত্যাগ: এই অ্যাপ্লিকেশনটি শুধুমাত্র তথ্যগত উদ্দেশ্যে প্রাথমিক চিকিৎসার নির্দেশিকা প্রদান করে এবং এটি পেশাদার চিকিৎসা পরামর্শ বা চিকিৎসার বিকল্প নয়।",
      "footer.logoAlt": "RapAID লোগো",
      "footer.description": "যখন সবচেয়ে বেশি প্রয়োজন, তখন দ্রুত, নির্ভরযোগ্য প্রাথমিক চিকিৎসার নির্দেশিকা প্রদান করা।",
      "header.logoAlt": "RapAID লোগো",
    }
  },
  ta: {
    translation: {
      "nav.home": "முகப்பு",
      "nav.categories": "வகைகள்",
      "nav.symptomChecker": "அறிகுறி சரிபார்ப்பு",
      "nav.about": "எங்களைப் பற்றி",
      "nav.emergency": "அவசரம்",
      "language": "மொழி",
      "hero.title": "உங்கள் விரல் நுனியில் விரைவான முதலுதவி வழிகாட்டுதல்",
      "hero.subtitle": "உங்களுக்கு மிகவும் தேவைப்படும்போது நம்பகமான முதலுதவி தகவலை அணுகவும். RapAID பல்வேறு அவசர சூழ்நிலைகளுக்கு தெளிவான, படிப்படியான வழிமுறைகளை வழங்குகிறது.",
      "hero.explore": "வகைகளை ஆராயுங்கள்",
      "hero.emergencyBtn": "அவசரம்",
      "hero.badge": "🚨 அவசர முதலுதவி உதவியாளர்",
      "search.placeholder": "முதலுதவி வழிகாட்டிகளைத் தேடுங்கள்...",
      "commonEmergencies.title": "பொதுவான அவசரநிலைகள்",
      "commonEmergencies.subtitle": "அடிக்கடி எதிர்கொள்ளும் சூழ்நிலைகளுக்கான வழிகாட்டிகளுக்கான விரைவான அணுகல்.",
      "categories.title": "அவசர வகைகள்",
      "categories.subtitle": "எங்கள் விரிவான அவசர முதலுதவி வழிகாட்டிகளின் வகைகளை உலாவுக. ஒவ்வொரு வகையிலும் விரிவான படிப்படியான வழிமுறைகள் உள்ளன.",
      "categories.viewAll": "அனைத்து வகைகளையும் காண்க",
      "symptomChecker.title": "மேம்பட்ட அறிகுறி சரிபார்ப்பு",
      "symptomChecker.subtitle": "என்ன தவறு என்று உறுதியாக தெரியவில்லையா? உங்கள் அறிகுறிகளை விவரிக்கவும், எங்கள் AI சாத்தியமான நிலையை அடையாளம் காணவும் பொருத்தமான முதலுதவி வழிகாட்டுதலை வழங்கவும் உதவும்.",
      "symptomChecker.checkNow": "இப்போது அறிகுறிகளைச் சரிபார்க்கவும்",
      "symptomChecker.aiBadge": "AI-இயங்கும்",
      "symptomChecker.commonSymptoms": "பொதுவான அறிகுறிகள்",
      "symptomChecker.possibleCondition": "சாத்தியமான நிலை: மாரடைப்பு",
      "symptomChecker.conditionDetail": "அறிகுறிகள் இதய அவசரநிலையைக் குறிக்கலாம். உடனடி மருத்துவ உதவியை நாடுங்கள்.",
      "symptomChecker.viewGuide": "முதலுதவி வழிகாட்டியைக் காண்க",
      "features.title": "அத்தியாவசிய அம்சங்கள்",
      "features.subtitle": "RapAID அவசரநிலைகளுக்கு திறம்பட பதிலளிக்க உங்களுக்கு உதவும் முக்கியமான அம்சங்களை வழங்குகிறது.",
      "feature.stepByStep": "படிப்படியான வழிகாட்டிகள்",
      "feature.stepByStepDesc": "பல்வேறு அவசர சூழ்நிலைகளுக்கான காட்சி உதவிகளுடன் தெளிவான, சுருக்கமான வழிமுறைகள்.",
      "feature.offline": "ஆஃப்லைன் அணுகல்",
      "feature.offlineDesc": "இணைய இணைப்பு இல்லாவிட்டாலும் முக்கியமான முதலுதவி தகவலை அணுகவும்.",
      "feature.voice": "குரல் உதவி",
      "feature.voiceDesc": "குரல் கட்டளைகள் மற்றும் ஆடியோ வழிமுறைகள் மூலம் ஹேண்ட்ஸ்-ஃப்ரீ வழிகாட்டுதல்.",
      "multiLanguage.title": "பல மொழி ஆதரவு",
      "multiLanguage.subtitle": "RapAID அதிக அணுகலுக்காக பல இந்திய மொழிகளில் முதலுதவி வழிமுறைகளை வழங்குகிறது.",
      "footer.quickLinks": "விரைவு இணைப்புகள்",
      "footer.categories": "அவசர வகைகள்",
      "footer.contact": "அவசர தொடர்பு",
      "footer.contactDesc": "அவசரநிலை ஏற்பட்டால், தயவுசெய்து உங்கள் உள்ளூர் அவசர சேவைகளை அழைக்கவும்.",
      "footer.copyright": "© 2026 RapAID. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
      "footer.disclaimer": "பொறுப்புத்துறப்பு: இந்த பயன்பாடு தகவல் நோக்கங்களுக்காக மட்டுமே முதலுதவி வழிகாட்டுதலை வழங்குகிறது மற்றும் தொழில்முறை மருத்துவ ஆலோசனை அல்லது சிகிச்சைக்கு மாற்றாக இல்லை.",
      "footer.logoAlt": "RapAID லோகோ",
      "footer.description": "மிகவும் தேவைப்படும்போது, விரைவான, நம்பகமான முதலுதவி வழிகாட்டுதலை வழங்குதல்.",
      "header.logoAlt": "RapAID லோகோ",
    }
  },
  te: {
    translation: {
      "nav.home": "హోమ్",
      "nav.categories": "వర్గాలు",
      "nav.symptomChecker": "లక్షణాల சரிபார்ப்பு",
      "nav.about": "మా గురించి",
      "nav.emergency": "అత్యవసరం",
      "language": "భాష",
      "hero.title": "మీ వేలికొనలకు త్వరిత ప్రథమ చికిత్స మార్గదర్శకత్వం",
      "hero.subtitle": "మీకు అత్యంత అవసరమైనప్పుడు నమ్మకమైన ప్రథమ చికిత్స సమాచారాన్ని యాక్సెస్ చేయండి. RapAID వివిధ అత్యవసర పరిస్థితుల కోసం స్పష్టమైన, దశల వారీ సూచనలను అందిస్తుంది.",
      "hero.explore": "వర్గాలను అన్వేషించండి",
      "hero.emergencyBtn": "అత్యవసరం",
      "hero.badge": "🚨 అత్యవసర ప్రథమ చికిత్స సహాయకుడు",
      "search.placeholder": "ప్రథమ చికిత్స గైడ్‌ల కోసం శోధించండి...",
      "commonEmergencies.title": "సాధారణ అత్యవసరాలు",
      "commonEmergencies.subtitle": "తరచుగా ఎదురయ్యే పరిస్థితుల కోసం గైడ్‌లకు త్వరిత ప్రాప్యత.",
      "categories.title": "అత్యవసర వర్గాలు",
      "categories.subtitle": "మా సమగ్ర అత్యవసర ప్రథమ చికిత్స గైడ్‌ల వర్గాలను బ్రౌజ్ చేయండి. ప్రతి వర్గంలో వివరణాత్మక దశల వారీ సూచనలు ఉంటాయి.",
      "categories.viewAll": "అన్ని వర్గాలను వీక్షించండి",
      "symptomChecker.title": "అధునాతన లక్షణాల சரிபார்ப்பு",
      "symptomChecker.subtitle": "ఏమి తప్పు జరిగిందో ఖచ్చితంగా తెలియదా? మీ లక్షణాలను వివరించండి మరియు మా AI సాధ్యమైన పరిస్థితిని గుర్తించడానికి మరియు తగిన ప్రథమ చికిత్స మార్గదర్శకత్వం అందించడానికి సహాయపడుతుంది.",
      "symptomChecker.checkNow": "ఇప్పుడే లక్షణాలను తనిఖీ చేయండి",
      "symptomChecker.aiBadge": "AI-ఆధారిత",
      "symptomChecker.commonSymptoms": "సాధారణ లక్షణాలు",
      "symptomChecker.possibleCondition": "సాధ్యమైన పరిస్థితి: గుండెపోటు",
      "symptomChecker.conditionDetail": "లక్షణాలు కార్డియాక్ అత్యవసరాన్ని సూచించవచ్చు. తక్షణ వైద్య సహాయం తీసుకోండి.",
      "symptomChecker.viewGuide": "ప్రథమ చికిత్స గైడ్‌ను వీక్షించండి",
      "features.title": "ముఖ్యమైన లక్షణాలు",
      "features.subtitle": "RapAID అత్యవసర పరిస్థితులకు సమర్థవంతంగా ప్రతిస్పందించడంలో మీకు సహాయపడటానికి కీలకమైన లక్షణాలను అందిస్తుంది.",
      "feature.stepByStep": "దశల వారీ గైడ్‌లు",
      "feature.stepByStepDesc": "వివిధ అత్యవసర పరిస్థితుల కోసం దృశ్య సహాయాలతో స్పష్టమైన, సంక్షిప్త సూచనలు.",
      "feature.offline": "ఆఫ్‌లైన్ యాక్సెస్",
      "feature.offlineDesc": "ఇంటర్నెట్ కనెక్షన్ లేకుండా కూడా కీలకమైన ప్రథమ చికిత్స సమాచారాన్ని యాక్సెస్ చేయండి.",
      "feature.voice": "వాయిస్ సహాయం",
      "feature.voiceDesc": "వాయిస్ ఆదేశాలు మరియు ఆడియో సూచనల ద్వారా హ్యాండ్స్-ఫ్రీ మార్గదర్శకత్వం.",
      "multiLanguage.title": "బహుళ భాషా మద్దతు",
      "multiLanguage.subtitle": "RapAID ఎక్కువ ప్రాప్యత కోసం బహుళ భారతీయ భాషలలో ప్రథమ చికిత్స సూచనలను అందిస్తుంది.",
      "footer.quickLinks": "త్వరిత లింకులు",
      "footer.categories": "అత్యవసర వర్గాలు",
      "footer.contact": "అత్యవసర సంప్రదింపు",
      "footer.contactDesc": "అత్యవసర పరిస్థితుల్లో, దయచేసి మీ స్థానిక అత్యవసర సేవలకు కాల్ చేయండి.",
      "footer.copyright": "© 2026 RapAID. అన్ని హక్కులు ప్రత్యేకించబడ్డాయి.",
      "footer.disclaimer": "నిరాకరణ: ఈ అప్లికేషన్ సమాచార ప్రయోజనాల కోసం మాత్రమే ప్రథమ చికిత్స మార్గదర్శకత్వం అందిస్తుంది మరియు వృత్తిపరమైన వైద్య సలహా లేదా చికిత్సకు ప్రత్యామ్నాయం కాదు.",
      "footer.logoAlt": "RapAID లోగో",
      "footer.description": "అత్యంత అవసరమైనప్పుడు, త్వరిత, నమ్మకమైన ప్రథమ చికిత్స మార్గదర్శకత్వం అందించడం.",
      "header.logoAlt": "RapAID లోగో",
    }
  }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    debug: false, 
    interpolation: {
      escapeValue: false, 
    },
    detection: {
      order: ['localStorage', 'navigator', 'htmlTag', 'path', 'subdomain'],
      caches: ['localStorage'],
    },
  });

export default i18n;